### ISSUE TITLE
$.ajaxPrefilter is not a function

### ISSUE THREAD

**Issue by jkolyer** [rails/jquery-ujs#182]
Latest version produces this error message

**Comment by bordemof** [comment]
This is still an issue

```
//= require jquery
//= require jquery_ujs

```
application-fe7c426….js:5570 Uncaught TypeError: $.ajaxPrefilter is not a function

JQuery version: 3.1.1 -ajax,-ajax/jsonp,-ajax/load,-ajax/parseXML,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-event/ajax,-effects,-effects/animatedSelector,-effects/Tween,-deprecated

**Comment by rcugut** [comment]
I was using the "**slim**" version of jQuery (my case:  jquery.3.2.1.slim.min) and got this error.

After I moved to using the complete version, this error doesn't show up anymore.

**Comment by fagbolaoluwagbenga** [comment]
well mine is w.ejsPrefilter is not a function
