### ISSUE TITLE
Event ajax:complete does not get triggered  after form-replacement

### ISSUE THREAD

**Issue by stayhero** [rails/jquery-ujs#223]
Hey.

Today I upgraded from jquery-rails gem 1.0.16 to 1.0.17. I found out that the "ajax:complete" event is not always triggered anymore. 

I prepared a simple Rails app to show the problem:
https://github.com/easychris/jquery17-rails-ujs-broken

In application.js I want to trigger all ajax:complete events for existing and new forms (hence the .live call):

``` javascript
$(function() {
  $('form').live('ajax:complete', function() {
    alert('ajax:complete event triggered');
  });
});
```

I prepared two sample data-remote=true forms, one page using jQuery 1.6.4, the other 1.7. The ajax call simply returns javascript code to replace the existing form by another form (in real life the new form would contain error messages etc). 

``` javascript
$('#test_form_container').html(' <%= j (render :partial => 'form')  %> ');
```

When using jQuery 1.6.4 the ajax:complete event gets triggered, but unfortunately not using 1.7. I found out that in jquery-ujs the line 

``` javascript
element.trigger('ajax:complete', [xhr, status]);
```

gets called, but it doesn't trigger any event. I guess because the form to which the ajax event belongs doesn't exist anymore (as it got replaced by the new form). But it should work, as I use the .live event to bind the event to any form-tag. And it does work in 1.6.4. 

Any ideas? I tried a couple of hours to find the error, without success. Maybe someone else already has an idea?

**Comment by shnikola** [comment]
I have solved this in application.js with the following:

```javascript
$('form').on('ajax:sendBefore', function(event, jqXHR) {
  jqXHR.always(onAjaxComplete);
});
```

**Comment by elfassy** [comment]
`ajaxSuccess` seems to always work (it's provided by js not rails-ujs)
```
$(document).on('ajaxSuccess', function(){
  $('form').removeClass("loading");
});
```

**Comment by elsurudo** [comment]
> If you want to replace the element that triggers an ajax request after the request is made, then your best bet is to respond with the HTML you want replaced and the replace it using jQuery in either the ajax:success or ajax:complete callback so that you have control over the order of events.

@JangoSteve Doesn't this sidestep a huge part of why `jquery-ujs` even exists? Namely, to submit forms remotely? If there is an error, then you likely want to replace the form so that you get the errors. IMO this is still a bug in this library and should be reopened, as it's not fully succeeding in its mission otherwise.

Responding with HTML sounds fine, but what if you want to replace, say, two elements? What is your EJS is too complicated? This doesn't sound like a tenable workaround, and all the other solutions are simply band-aids.

**Comment by feliperaul** [comment]
Why is this issue closed ? I'm on Rails 5.1 and still having this problem: `ajax:success` is never called if the original element is removed by the reponse.js.erb file.

**Comment by pinewong** [comment]
@lacco Thank you for your answer 👍 

When we use Rails 5.1 or later, add this gem:
```ruby
gem 'jquery-rails'
```
then change application.js
```js
//= require rails-ujs
```
to
```js
//= require jquery_ujs
```

now, everything will go will!

```coffee
# application.js
$(document).on "ajax:send", (event, jqXHR) ->
  # For ajax:send

  jqXHR.always ->
    # For ajax:complete
  jqXHR.done ->
    # For ajax:success
  jqXHR.fail ->
    # For ajax:erro
```

**Comment by radiantshaw** [comment]
@JangoSteve We are on `rails = 5.2.4.4` with `jquery-rails ~> 4.3.1` and the `ajax:complete` event does not get fired as well. I understand that it's not an issue with jQuery since that **is** how it's supposed to work. But maybe we can solve this by first firing the `ajax:complete` callback, and then executing the JS code received from the server?

**Comment by jq2034** [comment]
> Hey.
> 
> Today I upgraded from jquery-rails gem 1.0.16 to 1.0.17. I found out that the "ajax:complete" event is not always triggered anymore.
> 
> I prepared a simple Rails app to show the problem: https://github.com/easychris/jquery17-rails-ujs-broken
> 
> In application.js I want to trigger all ajax:complete events for existing and new forms (hence the .live call):
> 
> ```js
> $(function() {
>   $('form').live('ajax:complete', function() {
>     alert('ajax:complete event triggered');
>   });
> });
> ```
> 
> I prepared two sample data-remote=true forms, one page using jQuery 1.6.4, the other 1.7. The ajax call simply returns javascript code to replace the existing form by another form (in real life the new form would contain error messages etc).
> 
> ```js
> $('#test_form_container').html(' <%= j (render :partial => 'form')  %> ');
> ```
> 
> When using jQuery 1.6.4 the ajax:complete event gets triggered, but unfortunately not using 1.7. I found out that in jquery-ujs the line
> 
> ```js
> element.trigger('ajax:complete', [xhr, status]);
> ```
> 
> gets called, but it doesn't trigger any event. I guess because the form to which the ajax event belongs doesn't exist anymore (as it got replaced by the new form). But it should work, as I use the .live event to bind the event to any form-tag. And it does work in 1.6.4.
> 
> Any ideas? I tried a couple of hours to find the error, without success. Maybe someone else already has an idea?

https://jquerys.space/questions/utilize-either-the-success-or-complete-method-when-making-an-ajax-call

**Comment by Nile-gilt749** [comment]
> [@rfb](https://github.com/rfb) Yes I patched rails.js, locate the line that triggers the ajax:complete event
> 
> ```
> element.trigger('ajax:complete', [xhr, status]);
> ```
> 
> and replace with this code:
> 
> ```
> if (element.parents().last().parent().get(0) == document)
>   element.trigger('ajax:complete', [xhr, status]);
> else
>   $(document).trigger('ajax:complete', [xhr, status]);
> ```
> 
> It checks whether the element is still in the DOM, in which case simply triggers the event and if not triggers the event directly on the document. Because of this, you have to bind ajax:complete (or .live(), .delegate(), .on()) without a selector.





https://kaylenripe.github.io/I6yH-Sc5xjchf1qp0-uPilvD8f3Q1g/
