### ISSUE TITLE
Firefox 3.6.x form does not submit when containing required fields

### ISSUE THREAD

**Issue by mvilrokx** [rails/jquery-ujs#233]
When I add rails_ujs,js and I have required fields in my form, rails_ujs seems to prevent submission of my form, but no message gets displayed as to hinting why it is not getting submitted.  It basically ends up here:

// skip other logic when required values are missing or file upload is present
if (blankRequiredInputs && form.attr("novalidate") == undefined && rails.fire(form, 'ajax:aborted:required',[blankRequiredInputs])) {
  return rails.stopEverything(e);
}

In any other browser and version, it never even gets to this point, yet I get a message and it highlights the missing field.  I presume it is handled by the browser itself rather than the rails_ujs script.

Is there anything I can do about this so it is clear in FF 3.6 why it is not submitting?

Cheers,
Mark.

**Comment by labocho** [comment]
+1
I agree with @holli completely.
