### ISSUE TITLE
Cannot read property 'ownerDocument' of undefined when listening to ajax:success 

### ISSUE THREAD

**Issue by Sephi-Chan** [rails/jquery-ujs#311]
I encountered an issue with Ajax events.

When the user clicks the link to edit its message, a remote ajax request is done via data-remote and render a HTML form. This form is injected into the DOM with the ajax:success event of the link. This form is a data-remote one and when it's submitted, the request is successful but UJS fails at handling success event. It throw an error:

```
Cannot read property 'ownerDocument' of undefined
```

The source code is available on GitHub:
- Here are the events: https://github.com/Sephi-Chan/jeuweb/blob/a547903675f03a68c3e9d091c7b444697c5fe579/app/assets/javascripts/edit_reply.js.coffee
- And the injected form: https://github.com/Sephi-Chan/jeuweb/blob/a547903675f03a68c3e9d091c7b444697c5fe579/app/views/replies/edit.remote_html.haml

The crazy thing is that the form to edit the initial message (which inject https://github.com/Sephi-Chan/jeuweb/blob/a547903675f03a68c3e9d091c7b444697c5fe579/app/views/topics/edit.remote_html.haml) works well!

If you want, you can try this live by going on this page (http://jeuweb.bouh.org/topics/13-edition-bug). Just sign-in with test/test account and try to edit the message (the edit link appears when you roll over the message from test).

Thanks. :)

**Comment by Palanikumarsprw** [comment]
insert link is not work properly. it shows 
bootstrap3-wysihtml5.all.min.js:6 
Uncaught TypeError: Cannot read property 'ownerDocument' of undefinedwysihtml5.views.View.Base.extend.focus @ bootstrap3-wysihtml5.all.min.js:6a.views.Composer.a.views.View.extend.focus @ bootstrap3-wysihtml5.all.min.js:6c.function.c.valueOf.c.valueOf.b.valueOf.test.b @ bootstrap3-wysihtml5.all.min.js:3
