### ISSUE TITLE
a[disabled=disabled] for data-remote to disable ajax request on a link?

### ISSUE THREAD

**Issue by pothibo** [rails/jquery-ujs#317]
Since the data-remote links are handled with jquery-ujs, it's kinda hard to disable a link, I've added a feature on my fork to disable the ajax request when you set the attribute "disabled"

Here you can have a look at the commit(Tests are all green):

https://github.com/pothibo/jquery-ujs/commit/8eabf3a23f1c6de07df3ebd5c22a122fadb85390

Yay or nay?

**Comment by d3vkit** [comment]
I just ran across this trying to find a solution to disabling rails remote true links. Is there any plan to merge this in? What happened with this?

**Comment by pothibo** [comment]
I'm using this in many projects but I haven't heard anything from anyone. Since a few people already have shown interest in this feature, I'll make a PR and see where that goes.

**Comment by d3vkit** [comment]
:+1: That would be awesome!
