### ISSUE TITLE
Missing Vary Header

### ISSUE THREAD

**Issue by guilhermesimoes** [rails/jquery-ujs#318]
This bug occurs in Chrome and IE only but apparently [it is a problem on Rails' end](https://code.google.com/p/chromium/issues/detail?id=94369).

You can reproduce it by simply going to this page (https://secret-journey-4942.herokuapp.com/) and following the 3 steps indicated.

After hitting the back button, the browser will render the javascript returned by XHR to render the page instead of the actual page.

[Here's the repository](https://github.com/GuilhermeSimoes/chrome-bug) of the site that displays the bug.

This is fixed server-side by sending a Vary header, like so:

```
response.headers['Vary'] = 'Accept'
```

**Comment by nowhereman** [comment]
This bug also occurs in IE 10 and 11.
@guilhermesimoes Can you update your demo with jQuery 1.11.x then I could test it with IE 6, 7 and 8!

**Comment by guilhermesimoes** [comment]
It's been precisely 2 years since I reported this bug. Is jquery-ujs dead?

@rafaelfranca Has this been addressed in Rails at all? Do you know if Rails sends a Vary header?

**Comment by rafaelfranca** [comment]
No. Rails doesn't send a Vary header. And no jquery-ujs is not dead.

All work of Rails is volunteer and we don't have time to fix all the problems that people may have. If this is  a problem for you I recommend to propose a fix, or wait someone want to fix your problem.

**Comment by guilhermesimoes** [comment]
It's just that getting JSON or JavaScript when pressing the back button seems like a glaring bug to me. I'm surprised that in these 2 years more people haven't had this happen to them.

I guess it's just not that common to share the exact same URL for HTML pages and API endpoints.

**Comment by jonatack** [comment]
For the people commenting on this issue, this is free, open-source software (yay!) and you are more than welcome to make a pull request to improve it :heart:

**Comment by schneems** [comment]
Can anyone explain why this happens or give some specs or rational behind using "vary"? We've never set that header previously, why is this just now an issue?

**Comment by rafaelfranca** [comment]
I have no checked but I can see how this happens. Let say that we requested
/tasks/1 using Ajax, and the previous page has the same url. When we click
the back button the browser tries to get the response from its cache and it
gets the javascript response. With vary we "fix" this behavior because we
are telling the browser that the url is the same but it is not from the
same type what will skip the cache.

Although this fix the behavior I don't think it is a sane default for Rails
always send vary for accept header because this can cause unneeded cache
invalidations. But I can be wrong and with a deeper investigation we can
conclude that this default makes sense.

**Comment by guilhermesimoes** [comment]
@schneems This has been an issue for a long time. [Here's the original chromium issue](https://code.google.com/p/chromium/issues/detail?id=94369). There's even people specifically talking about Rails there.

Since I know that I can use a Vary header to correct this behavior, it hasn't bothered me that much. But I thought I'd ping you guys at this 2 year mark, that's all.

**Comment by JangoSteve** [comment]
So, if I'm reading this correctly, it sounds like it's an issue because the browser behavior concerning cached responses for the back (and I presume forward) button changed. Just to clarify, is the only down-side or side-effect that it will cause the browser to not cache AJAX responses when hitting back/forward buttons?

**Comment by guilhermesimoes** [comment]
The only downside is sending an extra header (that is probably useless in most cases). The browser keeps caching everything as usual (though it may opt not to use the cache).

Without the Vary header, the browser's back button leads to rendering what the server last returned, without taking cache directives into account - which is completely nonsensical in my opinion.

With the Vary header, the browser takes into account the Content-Type header before rendering what's cached.

In my opinion, Chrome and IE's behaviors are the ones that should change, not Rails'. We have Content-Type for a reason. But since they won't budge...

**Comment by jfirebaugh** [comment]
This is pretty clearly a bug in Rails. If the response body varies according to the Content-Type header, it needs to have `Vary: Content-Type` in order for downstream caches to know not to reuse cached content across different content-types.

> * Without the Vary header, the browser's back button leads to rendering what the server last returned, without taking cache directives into account

This is false -- without the `Vary: Content-Type` header, there _is no cache directive_ that the browser could take into account to inform it not to render what the server last returned.

> * With the Vary header, the browser takes into account the Content-Type header before deciding what to render from the cache.

Correct, which is exactly the correct and desired behavior.

**Comment by jfirebaugh** [comment]
For those interested in a spec reference, see [RFC 2616 14.44](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.44):

> An HTTP/1.1 server SHOULD include a Vary header field with any cacheable response that is subject to server-driven negotiation. Doing so allows a cache to properly interpret future requests on that resource and informs the user agent about the presence of negotiation on that resource.

"server-driven negotiation" is defined [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec12.html#sec12.1) and includes the `Accept`-based content type negotiation that we're discussing here.

**Comment by guilhermesimoes** [comment]
> This is false -- without the Vary: Accept header, there is no cache directive that the browser could take into account to inform it not to render what the server last returned.
Do you know what the Content-Type header is? Is there ever a use case in which you want JSON or JavaScript rendered back to you when you click the back button?

In any case, it seems like the Rails guys finally decided to fix this. Soon™

**Comment by guilhermesimoes** [comment]
🎉
