### ISSUE TITLE
data-disable-with keeps the button disabled when the user hit browser's back button

### ISSUE THREAD

**Issue by sobrinho** [rails/jquery-ujs#357]
If the user hits the browser's back button after submitting a form, the submit button is kept disabled, we must refresh the page to the restore the button state.

I found this workaround which seems to be working: [I lost the link]

It happens on Safari and Firefox, Chrome is fine.

Not sure about other browsers, I do not have any other here :)

**Comment by coderdave** [comment]
This is an old issue, but this is still occurring for me in, even in `v4.1.1`. The only difference is that it's not an `input`, it's just a regular link "button":

```ruby
<%= link_to "<i class='fa fa-plus fa-inverse'></i>".html_safe, new_appointment_path,
    class: "btn btn-success new pull-right", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i>" },
    id: "new_appointment_button", title: "New Appointment" %>
```
On first click, it spins, but when you hit the back button in Chrome for example, it stays spinning. Maybe something to do with turbolinks?

**Comment by bodhidharma-joe** [comment]
I fixed this by add $("button-class").prop('value', 'Submit') after the ajax submission. Basically it changes the button value back to the original one so that the button is not disabled anymore.
