### ISSUE TITLE
Custom confirm for data-confirm

### ISSUE THREAD

**Issue by bl4ckdu5t** [rails/jquery-ujs#400]
I don't want the default dialog of the data-confirm. However, I really need this and I will like to use [sweetalert][1] instead. I had earlier made a different approach towards this. Trying to intercept with ajax:beforeSend as in this [gist][2]. That failed because I couldn't have it to continue in the fallback. How can I got about this?

[1]:http://tristanedwards.me/sweetalert
[2]:https://gist.github.com/bl4ckdu5t/fc495bae88ca4811e446

**Comment by rafaelfranca** [comment]
You can just override the `$.rails.confirm` function. See https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L77

**Comment by matthewd** [comment]
@rafaelfranca I don't think you can, because anything other than the browser built-in will need a "what to do next" callback

**Comment by rafaelfranca** [comment]
Yes. That is true. You would have to block the execution of JavaScript to make it work.

**Comment by matthewd** [comment]
Presumably we *could* attempt to rearrange our behaviour (callbacks all the things) so it can work.. but I'm not sure it'd be particularly feasible.

**Comment by bl4ckdu5t** [comment]
Seems I'll have no choice than to use the default dialog. I tried overriding $.rails.confirm and I get my pretty dialog but then it doesn't do anything after confirmation.
```
$.rails.confirm = function(message){
     swal(message);
}
```
I hope this gets easier in the future

**Comment by lucasmazza** [comment]
This goes back to #196, where an ansyc implementation is available at https://github.com/JangoSteve/jquery-ujs/tree/async-confirm but it is a bit outdated. Would be awesome to see this landing on the main repo repo.
