### ISSUE TITLE
jQuery dependecy version on tag 1.0.0

### ISSUE THREAD

**Issue by lurraca** [rails/jquery-ujs#414]
Is there a reason on why the jQuery dependency version is set to '> 1.8' on tag 1.0.0 eb0e88537cd23208591c0426e8b06c1f0cfad39d when the library states that the requirement is jQuery '> 1.7'?

**Comment by rafaelfranca** [comment]
Where the library states that the requirement is > 1.7?

**Comment by rafaelfranca** [comment]
Just saw, in the file itself. It was a mistake. As you can see our README states 1.8 at the 1.0.0 tag https://github.com/rails/jquery-ujs/tree/v1.0.0#requirements
