### ISSUE TITLE
Fix JS to comply with LibreJS

### ISSUE THREAD

**Issue by pizzamaker** [rails/jquery-ujs#419]
The following scripts is still unfree/untagged/unrecognized by the LibreJS extension:

List of blocked JavaScript in https://diasporabr.com.br/stream

NONTRIVIAL: eval has been found in code
https://diasporabr.com.br/assets/jquery_ujs-5be99745d2e19d4e06fd99998b1cb99b.js

For more info, see: https://github.com/diaspora/diaspora/issues/6103

**Comment by rafaelfranca** [comment]
Thank you for the issue. There is no eval in our code so let us not how we can reproduce this issue.
