### ISSUE TITLE
Make this generic purpose.

### ISSUE THREAD

**Issue by SamMousa** [rails/jquery-ujs#420]
I like the idea of this unobtrusive JS, and I know this library is generic purpose and not rails specific...
So why is the file called rails.js?

Wouldn't it make more sense to name it the same as the bower repo?

**Comment by rafaelfranca** [comment]
Thank you for the issue. This library is maintained by the Rails team and we don't have any desire to make it generic to support other things that are not Rails. That said we don't have any reason to rename it.
