### ISSUE TITLE
Publish version 1.0.4 to NPM

### ISSUE THREAD

**Issue by ddgromit** [rails/jquery-ujs#423]
I'm replacing sprockets with webpack in my app and need to install this as a package.  The currently published version is 1.0.2 (which works) but I'd love to be able to get the latest version.  Could we get 1.0.4 published to npm?

**Comment by rafaelfranca** [comment]
I'm sorry but we don't support npm and we don't want to support. Wasn't the Rails team that published the package there so it would be great if you ask to who did it

**Comment by ddgromit** [comment]
No problem, makes sense.  /cc @callumacrae

**Comment by callumacrae** [comment]
Sorry about that, the developers of jquery-ujs are too lazy to support npm.

For reference, my shell history for the last thirty seconds:

```
j jquery-ujs
git fetch upstream
git rebase upstream/master
vim package.json # updating version number
git commit -am '1.0.4'
git push --follow-tags origin master
npm publish
```

Literally thirty seconds.

Come on, guys. I don't want to do this.

**Comment by jbhatab** [comment]
Is there anyway we can make this happen? We are working on a react webpack project within rails, https://github.com/shakacode/react_rails_server_rendering, and we need this on npm to keep all the assets in one place while still being able to leverage turbolinks.

I understand your reasoning though for why you haven't supported up until now.

**Comment by justin808** [comment]
@callumacrae My team needs this (https://github.com/shakacode/). If you can transfer the npm to us, we'll maintain this. @rafaelfranca We're happy to help. I just wrote about the options here: http://forum.railsonmaui.com/t/considerations-for-jquery-with-rails-and-webpack/344

**Comment by callumacrae** [comment]
Sure! What's your npm username?

Note that I've been pushing from my fork, which includes the package.json from #380: https://github.com/callumacrae/jquery-ujs

**Comment by justin808** [comment]
@callumacrae I just setup username "shakacode". We'll probably setup a fork off of your fork. Thanks so much. Please see the comment I posted to https://github.com/rails/jquery-ujs/pull/380.

**Comment by callumacrae** [comment]
I've added you:

```
❯ npm owner ls jquery-ujs
callumacrae <callum@macr.ae>
shakacode <justin@shakacode.com>
```

**Comment by justin808** [comment]
Thanks. Any need right now to publish a new version? Any way to get notified of when I need to do so?

**Comment by callumacrae** [comment]
1.1.0 was released the other day which needs publishing to npm. There isn't really any easy way to get notifications short of watching this repo, which could be noisy.

**Comment by justin808** [comment]
Version 1.1.0 is published: https://www.npmjs.com/package/jquery-ujs. Note, after publishing, I tried to change the readme. Sadly, you have to change the version number to update the readme. Thus the version on npm right now is `1.1.0-1`. In the future, we'll keep the version number the same as this project. In case I ever miss publishing an update, feel free to message me justin@shakacode.com.

[I documented this here](http://forum.railsonmaui.com/t/considerations-for-jquery-with-rails-and-webpack/344/3?u=justin):

This pull request has the changes:

https://github.com/shakacode/react-webpack-rails-tutorial/pull/88/files

To summarize:

1. Remove `jquery-rails` from your Rails `Gemfile`.
2. Add `jquery, jquery-ujs` to your list of entry points, in your webpack config, like [this][1].
3. Expose `jQuery` and `$` in your webpack config like [this][2].
4. Be sure to `bundle` and `npm install` and `npm shrinkwrap`, committing the updates to your `Gemfile.lock` and `npm-shrinwrap.json`.

**BOOM!** No more gemified `jquery-ujs` and `jquery`, and just one place to track dependency versions of your JavaScript! 


  [1]: https://github.com/shakacode/react-webpack-rails-tutorial/blob/421cef2b313c3e437ffa7e029f03bee0e41b9444/client/webpack.common.config.js#L9
  [2]: https://github.com/shakacode/react-webpack-rails-tutorial/blob/421cef2b313c3e437ffa7e029f03bee0e41b9444/client/webpack.common.config.js#L23

**Comment by justin808** [comment]
@callumacrae Looks like we need to update to 1.2.0.

@rafaelfranca How can @callumacrae and I be notified when you release new versions?

FWIW, we had 21,000 downloads last month: https://www.npmjs.com/package/jquery-ujs

**Comment by callumacrae** [comment]
Woah, that's actually a pretty serious number of downloads.

I've published 1.2.0. I pulled from the shakacode fork, merged in master from this repo, and then updated the package.json. I've pushed to my fork because I don't have push access to the shakacode fork: https://github.com/callumacrae/jquery-ujs

Note to jquery-ujs maintainers: you could have done this by running just `npm version 1.2.0 && npm publish`, which would also have handled the git tag for you. I'm amazed you're letting non-maintainers maintain what now seems to be a pretty serious distribution channel!

**Comment by justin808** [comment]
Turbolinks is going on npm:
https://github.com/rails/turbolinks/issues/658

![2016-02-03_10-03-53](https://cloud.githubusercontent.com/assets/1118459/12792028/b34458a4-ca5e-11e5-8211-d0e6b99fb6ad.png)

**Comment by rafaelfranca** [comment]
Cool!

**Comment by justin808** [comment]
@rafaelfranca, @callumacrae and I would love to hand over the keys to the npmjs. :wink: for jquery-ujs.

**Comment by justin808** [comment]
@sstephenson told me that he's too busy to take this one on.

**Comment by rafaelfranca** [comment]
same here

**Comment by justin808** [comment]
@rafaelfranca can you please notify either me or @callumacrae when you push a new release. We'd like to promptly update after you release.

**Comment by rafaelfranca** [comment]
https://github.com/rails/jquery-ujs/pull/380#issuecomment-48619529

> I'm happy to support alternative workflow, but this workflow should not require any more work from us.

notifying is still more work for us. I think you can use IFTTT https://ifttt.com/recipes/221968-email-me-when-a-github-repo-has-a-new-release

**Comment by justin808** [comment]
@rafaelfranca do you have a release script? Maybe that's something we can put in a PR, and then you just run the script.

We have one worked out for React on Rails: https://github.com/shakacode/react_on_rails/blob/master/rakelib%2Frelease.rake

We can leverage that work.

rake release[1.3.0]

and that will publish both to NPM and RubyGems

**Comment by rafaelfranca** [comment]
That doesn't work. To release to RubyGems is a completely different project. Again, I don't want to maintain something that is not officially supported. I agree with turbolinks being published with npm because it can be used in any web project but jquery-ujs is a Rails project.

**Comment by justin808** [comment]
@rafaelfranca How do you currently publish? If we wrote you a single command to run that publishes to both rubygems and npm, would that be more work?

CC: @callumacrae

**Comment by rafaelfranca** [comment]
Really sorry but I don't want to do this. I already gave all my reasons and
you keep trying to get me doing something that I don't want. I don't have
anything to add to this discussion.

**Comment by callumacrae** [comment]
Comparing the stats on RubyGems and npm, about 10% of jquery-ujs downloads come from from npm.

You care so little about this project that you're willing to let a third party with no vested interest in the project maintain a major release stream _to save two seconds typing?_ That's insane.

**Comment by rafaelfranca** [comment]
I'll say this again. I don't use and I don't plan to use npm. I don't want to maintain something that I don't use and I think have rights to do so. This is open source project, I'm not your employee. If you don't want to responsibility of maintaining it, neither do I. If one day I start to use npm I'll try to maintain it but it is not the case yet.

I care about this project for the Ruby on Rails perspective and usage and that is all. I'll continue to work in this project and fix other people problems with their usage with the Ruby on Rails blesed workflow because that is what I want to do.

**Comment by pixeltrix** [comment]
@callumacrae given that yesterday was [Time to Talk Day][1] in the UK and the acknowledged problems with mental health in the wider programming community please refrain from using language like 'insane' when describing the actions of another person within the community as it's against our [code of conduct][2].

I'm sure you meant nothing by the comment but please keep discussions civil and respectful.

[1]: http://www.time-to-change.org.uk/timetotalkday
[2]: http://rubyonrails.org/conduct/

**Comment by justin808** [comment]
It's worth noting that this project supports bower.

If you google "npm vs. bower": 
https://www.google.com/search?q=bower+vs+npm&gws_rd=ssl

It's pretty clear that NPM has won.

https://www.quora.com/Why-use-Bower-when-there-is-npm

Another example is that @dhh and @sstephenson will put put turbolinks on npm.

In any case, @callumacrae and my team at @shakacode (http://www.shakacode.com/) are more than happy to keep supporting jquery-ujs on npm.

**Comment by dhh** [comment]
Justin, I'm happy to see all the Rails JS on NPM. Our bottleneck has been having someone to do the work. If you and your team wants to do it, then by all means! Let's make it happen.

**Comment by justin808** [comment]
@dhh Any way that we can have all releases come from the same repo? There's a very number of tiny changes to make to this repo to make it happen. A single release script makes for just one command to update both RubyGems and NPM. In any case, I'm happy to help out where I can. Incidentally, we're getting great positive feedback on using webpack to package up npm JS for use in Rails on https://github.com/shakacode/react_on_rails. I go cover the objectives here: https://medium.com/@railsonmaui/the-react-on-rails-doctrine-3c59a778c724#.gs653wcfk.

**Comment by dhh** [comment]
Justin, I'd prefer not to make the NPM push yet another thing that Rails
core has to take care of. There are always things to debug and tweak. We
should have someone from the community who actually uses NPM deal with it.
So if you're interested in pursuing this, I'd suggest setting up a workflow
where you can push this yourself when a new release happens.

We're talking about dropping jquery-ujs in future versions anyway and go
with vanilla JS without a library for the simple functionality we need.

**Comment by callumacrae** [comment]
@dhh: Ooh, that sounds interesting. Is that discussion happening publicly? It's something I'd be interested in contributing to (not using jQuery is [kind of my thing](http://macr.ae/talks/how-to-not-use-jquery.html)).

**Comment by dhh** [comment]
Callum, so far it's just a thought. Vanilla JS has improved enough that the
jquery shimming isn't needed. If you want to take the lead on this, please
do!

**Comment by rzane** [comment]
Seems like someone has already taken on the challenge of a vanilla UJS. It's also on NPM.

https://github.com/hauleth/vanilla-ujs

**Comment by rafaelfranca** [comment]
@justin808 @callumacrae can you give me access to the npm package? I'll make it officially part of the release process. We have the actioncable precedent and we are using npm internally in Shopify too, so the situation changed.

**Comment by justin808** [comment]
@rafaelfranca Done for the github repo. I need an ID on npmjs.com.

**Comment by rafaelfranca** [comment]
my id on npmjs.com is rafaelfranca

**Comment by rafaelfranca** [comment]
Awesomw. Thank you!
