### ISSUE TITLE
Cross-domain check breaks in IE

### ISSUE THREAD

**Issue by lgustafson** [rails/jquery-ujs#426]
The new cross-domain check from 96561a2ac0fab58e3e248458e19003e09f106ec4 with IE7 and in IE compatibility mode always returns true when a form action is a path with no protocol or port.  This behavior prevents forms from being submitted in this scenario.  It appears that the cross-domain check depends on certain behavior that is not present in IE7 (or compatibility mode in later versions).  Namely, it assumes that when an anchor element's `href` property is set, that it will be converted to a fully qualified URL including protocol and hostname, and that these corresponding properties are set.  IE7 and compatibility mode does not convert the path to a fully qualified URL.

I would argue that within the function a partial URL missing the protocol and hostname should indicate that a cross-domain request is __not__ being made.

**Comment by lgustafson** [comment]
Raised issue in the wrong project.... .closing

**Comment by rafaelfranca** [comment]
Actually this is the right project.

**Comment by lgustafson** [comment]
Reopening, will take a look at tests and submit a new PR

**Comment by rafaelfranca** [comment]
:+1:

**Comment by dankohn** [comment]
Thanks for opening the issue and your proposed patch. We've been able to narrow down the problem further which is that IE8, when operating in IE7 mode (via a `<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />` header), is incorrectly seeing the server as cross domain. This breaks AJAX functionality, and so is an urgent bug.

From @blargoner who found the solution:
> In the case of a relative URL in IE7 mode, the value of urlAnchor.protocol is ":" (a string containing a single colon character), not an empty string, so it is not a falsey value as they seem to expect it should be in this case. This means the URL is still being erroneously treated as a cross-domain request.

Until a new version of rails-jquery with an updated rails-ujs is released, others are welcome to use this fork which contains the fix, accessible at:
```ruby
gem 'jquery-rails', github: 'spreemo/jquery-rails', ref: 'f4c96a8'
```
Here is the diff that fixed our issue. 
```diff
diff --git a/vendor/assets/javascripts/jquery_ujs.js b/vendor/assets/javascripts/jquery_ujs.js
index 1ee8859..71f8f30 100644
--- a/vendor/assets/javascripts/jquery_ujs.js
+++ b/vendor/assets/javascripts/jquery_ujs.js
@@ -176,10 +176,13 @@
         // This is a workaround to a IE bug.
         urlAnchor.href = urlAnchor.href;
 
-        // Make sure that the browser parses the URL and that the protocols and hosts match.
-        return !urlAnchor.protocol || !urlAnchor.host ||
-          (originAnchor.protocol + "//" + originAnchor.host !==
-            urlAnchor.protocol + "//" + urlAnchor.host);
+  // If URL protocol *and* host are false, assume it is not a
+  // cross-domain request (should only be the case for IE7 and IE
+  // compatibility mode).  Otherwise, evaluate protocol and host of the
+  // URL against the origin protocol and host
+        return !(((!urlAnchor.protocol || urlAnchor.protocol === ':') && !urlAnchor.host) ||
+     (originAnchor.protocol + "//" + originAnchor.host ===
+      urlAnchor.protocol + "//" + urlAnchor.host));
       } catch (e) {
         // If there is an error parsing the URL, assume it is crossDomain.
         return true;
```

**Comment by lgustafson** [comment]
Thanks @dankohn, I will update my PR with this change.

**Comment by lgustafson** [comment]
PR has been updated to include the fix from @dankohn and @blargoner
