### ISSUE TITLE
How to check if jquery-ujs is actually being used?

### ISSUE THREAD

**Issue by joaocunha** [rails/jquery-ujs#429]
I'm dealing with some legacy stuff that includes `jquery-ujs`. How can I check if it's _actually_ being used?

I know, it's sort of a dumb question, but due to the progressive enhancement approach of the library I'm having trouble identifying if it's serving any purpose - removing it doesn't seem to change anything, but you know, big codebases.

**Comment by cshold** [comment]
++. Same here. Not so dumb since it's a bit of a blanket helper.

**Comment by rafaelfranca** [comment]
The best I could think is check if the application has usage of the attributes that enable behaviors of this lib like `data-remote`, `data-disable-with` and so on.

Also, you always can remove and see what breaks :smile:.
