### ISSUE TITLE
Port to CoffeeScript.

### ISSUE THREAD

**Issue by cenouro** [rails/jquery-ujs#444]
Hey guys. Any chance we could start rewriting the code in CoffeeScript? I have searched a bit on the issues and it seems this has not been discussed yet. I think it could make the code a bit cleaner, although it is already well written.

**Comment by rafaelfranca** [comment]
I don't see any reason to. Javascript is just fine to write the code that we need and the maintainers are comfortable with it.

**Comment by jeremy** [comment]
@cenouro https://github.com/josh/rails-behaviors may interest you.

**Comment by cenouro** [comment]
@jeremy that's interesting, but it seems it is deprecated.

**Comment by jeremy** [comment]
@cenouro Yep, just for your interest.
