### ISSUE TITLE
Stripped down ujs for link_to delete action

### ISSUE THREAD

**Issue by dasibre** [rails/jquery-ujs#449]
for performance reasons, i'm trying to get just one link to post to a destroy action, which subsequently redirects the browser. My jQuery function tries to mimi ujs buy building a form, with hidden inputs and listening to onclick event to submit, using $.ajax(), which posts to my destroy action, but browser is not redirected after post.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
