### ISSUE TITLE
`submit.rails` event fails with radio buttons partially `required`

### ISSUE THREAD

**Issue by maisumakun** [rails/jquery-ujs#450]
In [W3C recommendation](http://www.w3.org/TR/html5/forms.html#the-required-attribute), there is only one `required` radio button necessary to make whole group required (this style is not recommended, though).

While this 'one required' style is valid as HTML5, it fails in the handling of `submit` event in jquery-ujs.

Form elements are filtered by `rails.requiredInputSelector` (currently `input[name][required]:not([disabled]),textarea[name][required]:not([disabled])`), so checked radio buttons without `required` attributes are omitted here. [Special treatment for required radio buttons](https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L320) can't recover because checked radios are no longer in `allInputs`.

**Comment by maisumakun** [comment]
seems fixed by [#457](https://github.com/rails/jquery-ujs/pull/457).

**Comment by rafaelfranca** [comment]
Thank you for confirming.
