### ISSUE TITLE
Unclear statement in wiki

### ISSUE THREAD

**Issue by Bartuz** [rails/jquery-ujs#453]
In your [wiki](https://github.com/rails/jquery-ujs/wiki/ajax#stoppable-events) we can read that: 

> If you stop ajax:before or ajax:beforeSend, the Ajax request will never take place.

But what does "stop" mean? Is it "return false" in 

```
 form.on('ajax:before', (() ->
    return false if 1 == 1
  ))
```

I think it should be specified & example given

**Comment by rafaelfranca** [comment]
Yes, it is. feel free to improve the wiki yourself if the example.
