### ISSUE TITLE
Rails ajax:success does not work

### ISSUE THREAD

**Issue by allencch** [rails/jquery-ujs#466]
With the jquery-rails 4.1.0, I have a simple view.html.erb
```
<%= link_to  'Test', '/test/ajax', remote: true, id: 'mytest'%>
```

Then in the corresponding controller based on the route,
```
  def ajax_test
    render json: {test: 'done'}
  end
```

And has a CoffeeScript, 
```
$ ->
        $('#mytest').on "ajax:success", (evt, data, status, xhr) ->
                alert 'Yes'
```

Then I get no alert after clicking the item. Using Chrome Inspect, I can get that XHR is success and get the response. But the ajax:success seems like doesn't work.

**Comment by rafaelfranca** [comment]
What happen if you do `$('body').on "ajax:success", (evt, data, status, xhr) ->`?

**Comment by allencch** [comment]
```
$ ->
        $(body).on "ajax:success", (evt, data, status, xhr) ->
                alert 'Yes'
```

```
$('body').on "ajax:success", (evt, data, status, xhr) ->
        alert 'Yes'

```

```
$ ->
        $(document).on "ajax:success", (evt, data, status, xhr) ->
                alert 'Yes'
```
None of the above work, except

```
$(document).on "ajax:success", (evt, data, status, xhr) ->
        alert 'Yes'
```

**Comment by rafaelfranca** [comment]
So that means that the `ajax:success` works but the binding is being made in the wrong time. We also have [tests to make sure this behavior works](https://github.com/rails/jquery-ujs/blob/72ca4f1a4ea205f94cf6c42c1bf7f0b90c429858/test/public/test/data-remote.js#L82) so could you please provide an example application reproducing the issue?

**Comment by allencch** [comment]
@rafaelfranca, thank you. In order to re-produce the problem, I found that it is caused by the second jquery.js which is included at the later of the page. Remove it solve the problem. This issue can be closed.
