### ISSUE TITLE
CSS :not() works only with "simple" selectors

### ISSUE THREAD

**Issue by AlexKVal** [rails/jquery-ujs#475]
According to https://www.w3.org/TR/css3-selectors/#negation
> The negation pseudo-class, :not(X), is a functional notation taking a simple selector as an argument.

In `:not(form button)` "form button" here is `a descendant combinator`
From https://www.w3.org/TR/css3-selectors/#combinators
> A descendant combinator is whitespace that separates two sequences of simple selectors.

Hence it is not a simple selector and because of that `:not(form button)` does not work.

This code [rails.js#L30](https://github.com/rails/jquery-ujs/blob/627913fc067399c26e5663fbd0a1719fc196af6b/src/)
```js
buttonClickSelector: 'button[data-remote]:not([form]):not(form button), button[data-confirm]:not([form]):not(form button)',
```
does not work because of `:not(form button)`

---
Proof http://codepen.io/anon/pen/vKQpmY?editors=1100#0.
`Standalone button` should have red text.

**Comment by liudangyi** [comment]
However, on Safari, `Standalone button` is red and `Button in form` is black. In early version of WebKit such as PhantomJS, this selector is considered illegal. But recent browsers should already support this.

**Comment by rafaelfranca** [comment]
It is a valid selector in jquery too.

**Comment by liudangyi** [comment]
Oops, Chrome doesn't support it even in the latest version (52). So this could be a problem in native UJS implementation.

**Comment by AlexKVal** [comment]
I must apologize for the confusion.

The `button[data-confirm]:not([form]):not(form button)` selector is used by `jQuery` in this library and `jQuery` gets it right.

The code
```js
$('button[data-confirm]:not([form]):not(form button)')
.css( "background-color", "red" )
```
works fine. The `Standalone Button` becomes red.

🍒
