### ISSUE TITLE
Force `data-remote="true"` on a link?

### ISSUE THREAD

**Issue by bboe** [rails/jquery-ujs#476]
Is it possible to disable other forms of opening links (middle click, cmd+click, etc)? We recently discovered a large handful of `MissingTemplate` exceptions for requests which appear to originate when our customers are opening a link in a new window or tab whose path is intended to return only responses to xhr requests.

One solution for us is to replace all such instances of `data-remote` on links with some other approach (e.g., not using links, or not using the `href` attribute), but it would be nice if there was a way to disable the unwanted behavior completely.

Perhaps this library could support a `data-href` field and look to that if `href` isn't provided?

**Comment by rafaelfranca** [comment]
This is outside of the scope of this library. You may be able to define your own event handlers for click and prevent users to open them in new windows although I consider this bad UX. I'd recommend to take a progressive enhancement approach or not use links at all for those cases.

**Comment by bboe** [comment]
> I'd recommend to take a progressive enhancement approach or not use links at all for those cases.

Yes, I think that's the way to go. Thanks.
