### ISSUE TITLE
wiki references broken library version

### ISSUE THREAD

**Issue by JelF** [rails/jquery-ujs#481]
At page https://github.com/rails/jquery-ujs/wiki/Asynchronous-call-to-confirm
there is a reference to https://github.com/akzhan/jquery-ujs/tree/asynchronous-call-to-confirm
which have broken tests, which results into auto-submiting non data-remote forms, which are handled via preventing submit event.
It also uses old jquery version, but upgrade is simple enough. According to this, it probably should be deleted from wiki or fixed by community

**Comment by rafaelfranca** [comment]
DOne
