### ISSUE TITLE
link_to two requests

### ISSUE THREAD

**Issue by uhtred** [rails/jquery-ujs#483]
When I require jquery-ujs using jquery-rails, all my link_to remote: true, trigger the request twice, not the event, just the request.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by uhtred** [comment]
Sorry, found the problem.
It happens using link_to remote AND reveal-ajax from foundation.
reveal-ajax and remote both trigger ajax to url.
