### ISSUE TITLE
Inconsistence in ajax callbacks

### ISSUE THREAD

**Issue by heaven** [rails/jquery-ujs#488]
Why are these arguments in different order for each callback? I mean is this intended?
```javascript
success: function(data, status, xhr) {
  element.trigger('ajax:success', [data, status, xhr]);
},
complete: function(xhr, status) {
  element.trigger('ajax:complete', [xhr, status]);
},
error: function(xhr, status, error) {
  element.trigger('ajax:error', [xhr, status, error]);
},
```
It makes impossible to use the same handler function for these events. I believe it should be xhr, status, data/error.

**Comment by Lax** [comment]
These are all original from jQuery.ajax(), see: 
https://api.jquery.com/jQuery.ajax/

I used to be confused by these problems for days, and found 
that `rails-ujs`(integrated in  rails-5.1) changes the parameters, 
see https://github.com/rails/rails/issues/29137

```javascript
document.body.addEventListener('ajax:success', function(event) {
  var detail = event.detail;
  var data = detail[0], status = detail[1],  xhr = detail[2];
})
```
