### ISSUE TITLE
Rails `remote: true` not making AJAX request

### ISSUE THREAD

**Issue by jonhue** [rails/jquery-ujs#495]
Whenever I click on a `link_to` with `remote: true` in my Rails 5.1 app, I get an `InvalidCrossOriginRequest` error. After turning off forgery protection the app ends up making a full `GET` request to the server and displays the javascript.

Here is the link:

    = link_to 'Example', example_url, remote: true

example.js.erb:

    $('.example').html('alert("example message")');

Route:

    scope :js, defaults: { format: :js } do
        #### Example
        get 'example', to: 'examples#example'
    end

Controller:

    def example
		respond_to do |format|
			format.html { redirect_to root_url, alert: 'Page not accessible' }
			format.js
		end
	end

---

I included the javascript in my template:

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

And I added the necessary js asset paths:

    //= require_self
    
    // jQuery
    //= require jquery
    //= require jquery_ujs

**Comment by gustavo-iha** [comment]
@jonhue, did it eventually get solved? I'm having the same trouble right now without jquery
