### ISSUE TITLE
does rails enforce data-method "GET" be uppercase?

### ISSUE THREAD

**Issue by nathanallen** [rails/jquery-ujs#507]
At a glance it seems possible that the `data-method` value could be a lowercase "get", which would fail this check

https://github.com/rails/jquery-ujs/blob/4b6e30f68ff1244fc0c790641d3408c2695a29bd/src/rails.js#L434

**Comment by jeremy** [comment]
Confirm, it could. Methods are uppercase, but lowercase usage is common and exhibited elsewhere. `data-method` is typically omitted entirely for GET requests, which may be why nobody has noticed. PR welcome to add support for lowercase `get` in this case 😊
