### ISSUE TITLE
not works as expected with rails-5.2

### ISSUE THREAD

**Issue by jerome-diver** [rails/jquery-ujs#510]
try to follow the guide and see that form helper form_with failed (or there is informations missing in the guide who is not to much didactic as long as it start with a title like "javascript unobstrusive" and show more than the half of his content with obstrusive javascript code....
Also, user need to add some gem like jquery-rails or not ? 
Finally, did you try to use with index.coffee ? I get a javascript an general error on rails-ujs with:
syntaxError: expected expression, got '<'
1. processResponse on rails-ujs.self at line 268

1. Rails.ajax/xhr< on rails-ujs.self line 196

1. createXHR/xhr.onreadystatechange on rails-ujs.self line 251

well... there is something wrong somewhere and it miss a lot of information (or infrmation is not really didactic) around how to use ajax and rails on the official guide. when i follow some tutos around this, it failed at some point with rails-ujs error).
Please tell me which kind of test information do you need to care about something around ajax and rails-5.2 ? (now it is version 5.2 supposed to be stable... correct ?)

ho... i disabled turbolinks as long as this other one buggy thing at versions 5 seems to be not ready to use without pain.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
