### ISSUE TITLE
Future of this gem

### ISSUE THREAD

**Issue by krtschmr** [rails/jquery-ujs#516]
since jQuery is dropped by most applications and by rails already, i wonder if this gem will be eventually given up?

rails-ujs is part of the rails core already and is maintained while this gem is 2 years old.
any thoughts?

**Comment by kaspth** [comment]
Still the same as any other repo: it’ll be maintained as long as there’s an active maintainer on it. 😄

If possible, I’d switch to rails-ujs if possible because it’s more likely to be maintained for now. Should hopefully be a drop-in replacement. Thanks!
