### ISSUE TITLE
Default Data-type with Accepts Header

### ISSUE THREAD

**Issue by JangoSteve** [rails/jquery-ujs#74]
This is in response to the comment threads [here](https://github.com/rails/jquery-ujs/commit/fbbefa0773d791d3a67b7a3bb971c10ca750131b) and [here](https://github.com/rails/jquery-ujs/commit/ff185db3198d4891ea5606e9dd9ef950a897f349).

The issue is that if the data-type of the remote request, set with the `dataType` parameter in jQuery's `.ajax()`, is not set, we would like the default behavior to request JavaScript from the server. The problem is that, if the controller does not have `respond_to :js` set as one of the acceptable formats, we don't want our preference to cause the application to error out.

For this reason, rails.js has been modified to no longer set the default data-type to 'script'. As a result, if the data-type is not set explicitly, remote requests are sent with an Accepts header of `'*/*'`, which causes the controller to respond with the first format listed in the Responder.

So, if the controller has:

```
respond_to :html, :js
```

or:

```
respond_with(@object) do |format|
    format.html { }
    format.js { }
end
```

It will respond with HTML as the default AJAX response, which is counter-intuitive. To fix this, we must reverse the order of the JS and HTML format declarations such that the JS is first. This is confusing and not immediately apparent.

What if we could tell the server that we'd prefer JS, but if it's not an acceptable data-type (i.e. the JS format is not defined in the Responder), then to just return whatever it's got? Actually, we can, with the following code in the `beforeSend` callback in our `$.ajax()` method:

```
beforeSend: function(xhr, settings) {
    if ( settings.dataType == undefined ) {
        xhr.setRequestHeader("Accept", "text/javascript, */*; q=0.5");
    }
    return fire(element, 'ajax:beforeSend', xhr);
},
```

According to [the Accepts header and q-parameter definitions](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), this tells the server precisely, "I'd prefer javascript, but if you don't have it, I'll take whatever you've got."

I tested this in my own rails.js file, and sure enough it works as expected. Whether I have `respond_to :js, :html` or `respond_to :html, :js`, it always responds with JS. If I take out the `:js` and just have `respond_to :html`, then it responds with the HTML.

I can submit a pull request with this if everyone's on board.

**Comment by x-yuri** [comment]
@mislav I just wanted to ask how `*/*;q=0.5, text/javascript, application/javascript` is more correct than `text/javascript, application/javascript, */*;q=0.5`...

**Comment by mislav** [comment]
@x-yuri I can't remember, to be honest. This was from the time that my commit messages weren't descriptive enough, it seems. With `Mime::Type.parse` behavior in recent versions of Rails, both strings are parsed in an identical way. Maybe at the time of me making that commit, the `Accept` header parsing was more limited and order mattered.
